### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/leeainu#2]

**Comment by chrzyki** [comment]
In the sense of fixing the buildbot warnings? I can take care of that.

**Comment by SimonGreenhill** [comment]
It's also got a custom csv reader, lots of loops, and doesn't use the add_x helper functions. Would love it if you could have a look?

**Comment by chrzyki** [comment]
Sure, will do!

**Comment by chrzyki** [comment]
Heya @SimonGreenhill, I've update the dataset and improved a couple of smaller things and fixed all buildbot warnings. I've yet to address the somewhat unwieldy custom code & readers.

**Comment by SimonGreenhill** [comment]
Awesome, thanks @chrzyki!

**Comment by SimonGreenhill** [comment]
perhaps comparing to https://github.com/lexibank/leejaponic/blob/master/lexibank_leejaponic.py might help (these should be similar data formats as they're from the same person)

**Comment by chrzyki** [comment]
Good point, I'll try and mirror these for more transparency and easier maintainability.
